FROM node:12-alpine AS build

# install dependencies first, in a different location for easier app bind mounting for local development
RUN mkdir /opt/react-app
WORKDIR /opt/react-app
COPY package.json package-lock.json .npmrc ./
RUN npm install
ENV PATH /opt/react-app/node_modules/.bin:$PATH

# copy in our source code last, as it changes the most
WORKDIR /opt/react-app/app
COPY . .

# Add bash
RUN apk add --no-cache bash

RUN chmod +x ./scripts/env.sh

CMD npm start
