export default {
	fragments: [
		{
			id: 56357,
			created_at: '2017-04-10T10:29:56Z',
			updated_at: '2017-04-10T10:29:56Z',
			collection_id: 141,
			custom_description:
				'Deze collectie is gemaakt voor lessen binnen het vak economie en bedrijfsbeheer in de tweede en de derde graad van het secundair onderwijs.',
			custom_title: 'INLEIDING',
			end_oc: null,
			external_id: null,
			mediamosa_id: null,
			position: 1,
			start_oc: null,
		},
		{
			id: 2345,
			created_at: '2017-04-10T10:29:56Z',
			updated_at: '2017-04-10T10:29:56Z',
			collection_id: 141,
			custom_description: 'Test.',
			custom_title: 'WIN',
			end_oc: 25,
			external_id: {
				external_id: '9c6rx9m46j',
				id: 12737,
				mediamosa_id: 'i2XXZLeTXL5SKsFGhXo1hsUI',
				type_label: 'video',
			},
			mediamosa_id: 'i2XXZLeTXL5SKsFGhXo1hsUI',
			position: 2,
			start_oc: 15,
		},
		{
			id: 546,
			created_at: '2017-04-10T10:29:56Z',
			updated_at: '2017-04-10T10:29:56Z',
			collection_id: 141,
			custom_description:
				'Begingeneriek van Schooltelevisie met een aaneenschakeling van cartoons in verband met verzekeringen en situaties waarbij een verzekering handig of nodig kan zijn.',
			custom_title: 'Eigen titel',
			end_oc: null,
			external_id: {
				external_id: '9c6rx9m46j',
				id: 12737,
				mediamosa_id: 'i2XXZLeTXL5SKsFGhXo1hsUI',
				type_label: 'video',
			},
			mediamosa_id: 'i2XXZLeTXL5SKsFGhXo1hsUI',
			position: 3,
			start_oc: null,
		},
		{
			id: 2,
			created_at: '2017-04-10T10:29:56Z',
			updated_at: '2017-04-10T10:29:56Z',
			collection_id: 141,
			custom_description:
				'Een animatiefilm uit Voor hetzelfde geld in verband met verzekeringen. Het verschil tussen verplichte en niet-verplichte verzekeringen wordt aangehaald. Enkele voorbeelden van absurde verzekeringen worden opgesomd.',
			custom_title: '2. Verzekeringen: soorten en nuttigheid',
			end_oc: 2293,
			external_id: {
				external_id: 'db7vm4kp89',
				id: 12694,
				mediamosa_id: 'i2MTbGIyalfSMcQIfKn2dVa2',
				type_label: 'video',
			},
			mediamosa_id: 'i2MTbGIyalfSMcQIfKn2dVa2',
			position: 4,
			start_oc: 2220,
		},
	],
	title: 'Verzekeringen',
	is_public: false,
	id: 1316041,
	lom_references: [],
	type_id: 3,
	created_at: '2017-11-21',
	updated_at: '2017-11-21',
	organisation_id: '0',
	mediamosa_id: 'R6XgdX5QYCNJMcnpJt5tWD4v',
	owner_id: {
		created_at: '2014-01-27T15:11:39',
		id: 1,
		mail: 'support+testbeeld@viaa.be',
		name: 'Admin',
		role_id: 81,
		status_id: null,
	},
};
