export enum QUERY_KEYS {
	GET_CONTENT_PAGE_BY_PATH = 'GET_CONTENT_PAGE_BY_PATH',
	GET_ASSIGNMENTS_EDIT_STATUSES = 'GET_ASSIGNMENTS_EDIT_STATUSES',
	GET_COLLECTIONS_EDIT_STATUSES = 'GET_COLLECTIONS_EDIT_STATUSES',
	GET_LOM_FIELDS = 'GET_LOM_FIELDS',
	GET_QUALITY_LABELS = 'GET_QUALITY_LABELS',
	GET_INTERACTIVE_TOUR_FOR_PAGE = 'GET_INTERACTIVE_TOUR_FOR_PAGE',
}
