export const RouteParts = {
	Search: 'zoeken',
	Item: 'item',
	Folder: 'map',
	Collection: 'collectie',
	Collections: 'collecties',
	MyWorkspace: 'mijn-werkruimte',
	Bookmarks: 'bladwijzers',
	Folders: 'mappen',
	LoginAvo: 'login-avo',
	Logout: 'afmelden',
	Register: 'registreren',
	RegisterOrLogin: 'registreer-of-login',
	Discover: 'ontdek',
	Projects: 'projecten',
	News: 'nieuws',
	Edit: 'bewerk',
	Create: 'maak',
	Detail: 'detail',
	Assignments: 'opdrachten',
	Assignment: 'opdracht',
	Responses: 'indieningen',
	SearchQuery: 'zoekopdracht',
	Admin: 'beheer',
	Menus: 'navigatie',
};
