/// <reference types="react-scripts" />
declare module 'flowplayer-files';
declare module 'capture-stack-trace';
declare module 'react-meta-tags';
declare module 'recursive-omit-by';
declare module 'react-copy-to-clipboard';
declare module 'unique-selector';
declare module 'sanitize-html';
declare module 'fs-extra';
declare module 'react-to-string';
declare module '@flowplayer/player/plugins/chromecast';
declare module '@flowplayer/player/plugins/airplay';
declare module '@flowplayer/player/plugins/subtitles';
declare module '@flowplayer/player/plugins/hls';
declare module '@flowplayer/player/plugins/cuepoints';
declare module '@flowplayer/player/plugins/keyboard';
declare module '@flowplayer/player/plugins/playlist';
declare module '@flowplayer/player/plugins/speed';
declare module '@flowplayer/player/plugins/google-analytics';
