.ONESHELL:
SHELL = /bin/bash

.PHONY: all test

test:
	echo disabeld to test flow
#	chown node:node $${WORKSPACE} -R
#	cd ./tests
#	npm run unit-tests
#	npm run test:e2e:install-chrome
#	npm run test:e2e
